-- 為 MISSION 表添加用戶ID欄位
ALTER TABLE MISSION ADD COLUMN MUSER_ID INT NOT NULL DEFAULT 1;

-- 添加外鍵約束
ALTER TABLE MISSION ADD FOREIGN KEY (MUSER_ID) REFERENCES USER(UID) ON DELETE CASCADE;

-- 更新現有任務的用戶ID（可選，如果有現有資料的話）
-- UPDATE MISSION SET MUSER_ID = 1 WHERE MUSER_ID = 0;