USE rpg_project;

CREATE TABLE USER (
    UID INT AUTO_INCREMENT PRIMARY KEY,
    UUSERNAME VARCHAR(50) NOT NULL,
    UEMAIL VARCHAR(100) NOT NULL UNIQUE,
    ULEVEL INT NOT NULL DEFAULT 1,
    UEXP INT NOT NULL DEFAULT 0,
    UCREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MISSION (
    MID INT AUTO_INCREMENT PRIMARY KEY,
    MCATEGORY VARCHAR(50),
    MDESCRIPTION TEXT,
    MDIFFICULT TEXT,
    MGOAL_EXP INT,
    MGOAL_LEVEL INT,
    MCREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MFINISHED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LEVEL_TITLE (
    LTID INT AUTO_INCREMENT PRIMARY KEY,
    LTLEVEL_NAME VARCHAR(100) NOT NULL UNIQUE,
    LTNEED_EXP INT NOT NULL,
    LTGET_STATUS TINYINT(1) NOT NULL DEFAULT 0,
    LTTITLE_PICTURE VARCHAR(255) NOT NULL UNIQUE,
    LTCREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);