-- 創建完整的資料庫表結構

-- 創建用戶表
CREATE TABLE IF NOT EXISTS USER (
    UID INT AUTO_INCREMENT PRIMARY KEY,
    UUSERNAME VARCHAR(50) NOT NULL UNIQUE,
    UEMAIL VARCHAR(100) NOT NULL UNIQUE,
    UPASSWORD VARCHAR(255) NOT NULL,
    ULEVEL INT DEFAULT 1,
    UEXP INT DEFAULT 0,
    UCREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UUPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 創建等級稱號表
CREATE TABLE IF NOT EXISTS LEVEL_TITLE (
    LTID INT AUTO_INCREMENT PRIMARY KEY,
    LTLEVEL_NAME VARCHAR(100) NOT NULL UNIQUE,
    LTNEED_EXP INT NOT NULL,
    LTGET_STATUS TINYINT(1) NOT NULL DEFAULT 0,
    LTTITLE_PICTURE VARCHAR(255) NOT NULL UNIQUE
);

-- 創建任務表
CREATE TABLE IF NOT EXISTS MISSION (
    MID INT AUTO_INCREMENT PRIMARY KEY,
    UID INT NOT NULL,
    MCATEGORY VARCHAR(100) NOT NULL,
    MDESCRIPTION TEXT,
    MDIFFICULT ENUM('Easy', 'Medium', 'Hard') DEFAULT 'Easy',
    MGOAL_EXP INT DEFAULT 0,
    MGOAL_LEVEL INT DEFAULT 1,
    MCREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MFINISHED_AT TIMESTAMP NULL,
    MSTATUS ENUM('pending', 'in_progress', 'completed') DEFAULT 'pending',
    FOREIGN KEY (UID) REFERENCES USER(UID) ON DELETE CASCADE
);

-- 創建用戶稱號關聯表（可選，如果需要單獨追蹤用戶獲得的稱號）
CREATE TABLE IF NOT EXISTS USER_TITLES (
    UTID INT AUTO_INCREMENT PRIMARY KEY,
    UID INT NOT NULL,
    LTID INT NOT NULL,
    UEARNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UID) REFERENCES USER(UID) ON DELETE CASCADE,
    FOREIGN KEY (LTID) REFERENCES LEVEL_TITLE(LTID) ON DELETE CASCADE,
    UNIQUE KEY unique_user_title (UID, LTID)
);

-- 插入預設的等級稱號資料
INSERT INTO LEVEL_TITLE (LTLEVEL_NAME, LTNEED_EXP, LTGET_STATUS, LTTITLE_PICTURE) VALUES
('Novice Adventurer', 0, 1, 'lv1.png'),
('Apprentice Explorer', 500, 0, 'lv2.png'),
('Skilled Warrior', 1000, 0, 'lv3.png'),
('Veteran Fighter', 1500, 0, 'lv4.png'),
('Expert Guardian', 2000, 0, 'lv5.png'),
('Master Defender', 2500, 0, 'lv6.png'),
('Elite Champion', 3000, 0, 'lv7.png'),
('Legendary Hero', 3500, 0, 'lv8.png'),
('Mythical Warrior', 4000, 0, 'lv9.png'),
('Divine Protector', 4500, 0, 'lv10.png'),
('Celestial Guardian', 5000, 0, 'lv11.png'),
('Immortal Legend', 5500, 0, 'lv12.png'),
('Transcendent Master', 6000, 0, 'lv13.png'),
('Eternal Champion', 6500, 0, 'lv14.png'),
('Ultimate Deity', 7000, 0, 'lv15.png')
ON DUPLICATE KEY UPDATE LTLEVEL_NAME = VALUES(LTLEVEL_NAME);